version: "3.7"

networks:
  mysql_practice:

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=homedatabase
      - MYSQL_DATABASE=mysqlpractice
    ports:
      - 3307:3306
    networks:
      - mysql_practice
    volumes:
      - /data/mysqlpractice/mysql:/var/lib/mysql
      - ./mycustom.cnf:/etc/mysql/conf.d/mysql.cnf
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  backend_express:
    build:
      context: ./backend_express
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - BACKEND_PORT=3000
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=mysqlpractice
      - MYSQL_ROOT_PASSWORD=homedatabase
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - mysql_practice
    volumes:
      - ./backend_express:/usr/src/app/backend

#  backend_nest:
#    build:
#      context: ./backend_nest
#      dockerfile: Dockerfile
#    ports:
#      - 3000:3000
#    volumes:
#      - ./backend_nest:/usr/src/app/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:3000
    depends_on:
      - backend_express
    links:
      - backend_express
    volumes:
    - ./frontend:/usr/src/app/frontend
