version: "3.7"

networks:
  mysql_practice:

services:
  mysql:
    image: mysql:8
    restart: always
    env_file:
      - ./mysql/.env
    ports:
      - 3307:3306
    networks:
      - mysql_practice
    volumes:
      - ~/data/mysqlpractice/mysql:/var/lib/mysql
      - ./mycustom.cnf:/etc/mysql/conf.d/mysql.cnf

  rabbit:
    image: rabbitmq:3.7.18-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=randomString
      - RABBITMQ_DEFAULT_PASS=randomString
      - RABBITMQ_ERLANG_COOKIE=randomString
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management path_prefix "/rabbit"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mysql_practice
    volumes:
      - ~/rabbit:/var/lib/rabbitmq

  backend_express:
    build:
      context: ./backend_express
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - backend_express/.env
    depends_on:
      - mysql
      - rabbit
    links:
      - mysql
      - rabbit
    networks:
      - mysql_practice

  uploader:
    build:
      context: ./uploader
      dockerfile: Dockerfile
    env_file:
      - ./uploader/.env
    ports:
      - 4000:4000
    depends_on:
      - mysql
      - rabbit
    links:
      - mysql
      - rabbit
    networks:
      - mysql_practice

#  backend_nest:
#    build:
#      context: ./backend_nest
#      dockerfile: Dockerfile
#    ports:
#      - 3000:3000
#    volumes:
#      - ./backend_nest:/usr/src/app/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:3000
    depends_on:
      - uploader
      - backend_express
    links:
      - uploader
      - backend_express
    networks:
      - mysql_practice
