const BOOKS_TABLE_NAME = 'books';
const AUTHORS_TABLE_NAME = 'authors';
const TAGS_TABLE_NAME = 'tags';
const BOOK_AUTHOR_TABLE_NAME = 'book_author';
const BOOK_TAG_TABLE_NAME = 'book_tag';

const VALID_TABLES_ARRAY = [
    BOOKS_TABLE_NAME,
    AUTHORS_TABLE_NAME,
    TAGS_TABLE_NAME,
    BOOK_AUTHOR_TABLE_NAME,
    BOOK_TAG_TABLE_NAME,
];

export {
    BOOKS_TABLE_NAME,
    AUTHORS_TABLE_NAME,
    TAGS_TABLE_NAME,
    BOOK_AUTHOR_TABLE_NAME,
    BOOK_TAG_TABLE_NAME,
    VALID_TABLES_ARRAY
}